INSERT INTO Writer (ID, W_NAME)
    VALUES(1, Josh Homme),
    VALUES(1, Nick Oliver),
    VALUES(2, Max Martin),
    VALUES(2, Abel Tesfaye),
    VALUES(2, Alex Hedfors),
    VALUES(2, Carl Nordstrom),
    VALUES(2, Kevin Duane Mccord),
    VALUES(2, Oscar Holter),
    VALUES(2, Sebastian Ingrosso),
    VALUES(2, Steve Angello),
    VALUES(3, BloodPop),
    VALUES(3, Max Martin),
    VALUES(3, Ely Rise),
    VALUES(3, Lady Gaga),
    VALUES(3, Martin Bresso),
    VALUES(4, Julian Casablancas),
    VALUES(5, Ozzy Osbourne),
    VALUES(5, Tony Lommi),
    VALUES(5, Geezer Butler),
    VALUES(5, Bill Ward),
    VALUES(6, Eddie Clarke),
    VALUES(6, Lemmy Kilmister),
    VALUES(6, Phil Taylor),
    VALUES(7, Jeff Rosenstock),
    VALUES(8, Alexi Berrow),
    VALUES(9, Tomas Kalnoky),
    VALUES(10, Brendan Taylor Francis),
    VALUES(10, Jacob Starnes Ewald),
    VALUES(10, Ian Daniel Farmer),
    VALUES(10, Sean Edward Huber),
    VALUES(11, Micheal Tomas Kinsella),
    VALUES(11, Steven Joseph Lamos),
    VALUES(11, Stephen Michael Holmes),
    VALUES(12, Fatter Than Albert),
    VALUES(13, Thom Yorke),
    VALUES(13, Jonny Greenwood),
    VALUES(13, Ed OBrien),
    VALUES(13, Colin Greenwood),
    VALUES(13, Philip Selway),
    VALUES(14, Ethan Kath),
    VALUES(15, Anton Zaslavski),
    VALUES(15, Holly Hafermann),
    VALUES(15, Matthew Koma),
    VALUES(15, Porter Robinson),
    VALUES(16, Willie Maxwell),
    VALUES(17, Anthony Didio),
    VALUES(17, Jeremy Martin),
    VALUES(17, Mirsy),
    VALUES(17, Matt Wood),
    VALUES(18, Bob Marley),
    VALUES(19, Don Alan Schlitz Jr),
    VALUES(20, Rod Temperton),
    VALUES(20, Steven Tyler),
    VALUES(20, Tom Hamilton),
    VALUES(21, A Baker),
    VALUES(21, Afrika Bambaataa),
    VALUES(21, Arthur Baker),
    VALUES(21, E Williams),
    VALUES(21, J Miller),
    VALUES(21, J Robie),
    VALUES(21, R Allen),
    VALUES(21, The Soulsonic Force),
    VALUES(22, S Goodman),
    VALUES(23, Jimmy Webb),
    VALUES(24, Jimmy Bain),
    VALUES(24, Ronnie James Dio),
    VALUES(24, Vincent Appice),
    VALUES(24, Vinny Appice),
    VALUES(24, Vivian Campbell),
    VALUES(25, Giorgio Tuinfort),
    VALUES(25, Sam Martin),
    VALUES(25, Jason Evigan),
    VALUES(25, Lindy Robbins),
    VALUES(26, Brendon Urie),
    VALUES(26, Ryan Ross),
    VALUES(26, Spencer Smith),
    VALUES(27, Dawid Podsiadlo),
    VALUES(27, Bogdan Kondracki),
    VALUES(28, Kevin Churko),
    VALUES(28, Dan Donegan),
    VALUES(28, Mike Wengren),
    VALUES(28, David Draiman),
    VALUES(29, Francesco Sartori),
    VALUES(29, Lucio Quarantotto),
    VALUES(30, Benito Benitez);
    VALUES(30, John Garrett III);
    VALUES(30, Thea Austin);
